#!/bin/sh
# SGI
#PBS -V
#PBS -N divtime
#PBS -e divtime.err
#PBS -o divtime.out
#PBS -q workq
#PBS -l place=scatter
#PBS -l select=1:ncpus=32
#PBS -l walltime=400:00:00
# shm, sock, ssm, rdma, rdssm
FABRIC=rdma
#CORES=$[ `cat $PBS_NODEFILE | wc -l` ]
#NODES=$[ `uniq $PBS_NODEFILE | wc -l` ]

#printf "Current time is: `date`\n";
#TEND = 
#printf "Current PBS work directory is: $PBS_O_WORKDIR\n";
#printf "Current PBS queue is: $PBS_O_QUEUE\n"; 
#printf "Current PBS job ID is: $PBS_JOBID\n";
#printf "Current PBS job name is: $PBS_JOBNAME\n";
#printf "PBS stdout log is: $PBS_O_WORKDIR/sgi_mpitest.err\n";
#printf "PBS stderr log is: $PBS_O_WORKDIR/sgi_mpitest.log\n";
#printf "Fabric interconnect selected is: $FABRIC\n";
#printf "This jobs will run on $CORES processors.\n";
##. /etc/profile.d/modules.sh
#module load gnu8 openmpi3 && echo "Successfully load modules"

cd $PBS_O_WORKDIR
pwd

# add zlib to the path so that openmpi can find it
#export LD_LIBRARY_PATH=/apps/ZLIB128/lib/:$LD_LIBRARY_PATH
# export path to my mpi
#echo $PATH
export PATH=$HOME/programs/miniconda3/bin:$PATH
source activate mrbayes
#export PATH="/home/gustavo/programs/julia-1.10.1/bin:$PATH"
which mrbayes_volpiano-mpi

#printf "mpiexec_mpt run command location is: `which mpiexec_mpt`\n";
#printf "\n[STAT] qstat -f $PBS_JOBID\n";
#qstat -f $PBS_JOBID
#printf "\n[END] qstat -f $PBS_JOBID\n";
#TBEGIN=`echo "print time();" | perl`

#MPI_HOSTS=$(sort $PBS_NODEFILE | uniq -c | \
#awk '{print $2 " " $1}' | \
#tr "\n" "," | \
#sed 's/.$//')

###########
# COMMAND #
###########

mpirun -np 32 -oversubscribe mrbayes_volpiano-mpi concatenated.mb > divtime.outerr 2>&1 
